### ISSUE TITLE
how to compile g2o on my machine?

### ISSUE THREAD

**Issue by imranq** [geohot/twitchslam#7]
I always get the error, module not found for import g2o

**Comment by plasticuproject** [comment]
You are missing the General Graph Optimization dependency...

https://github.com/uoip/g2opy


There are lots of dependencies that he didn't include in this repo. I think he plans on including a list at some point, or a build script, but for now you just have to browse the code or keep following the compiling errors until you get it working. I'd give you a list but I'm not at my machine right now.

**Comment by imranq** [comment]
Thanks! I tried cloning that repository and installing the dependencies and following the build commands but it still fails

**Comment by plasticuproject** [comment]
What fails exactly? There are a lot of libraries used to get this implentation to work. I feel that this is a dependency issue, and if you are having trouble installing those dependencies you should close this issue until you have accurately tracked down and documented the problem.

If you are facing an issue with g2o, post an open issue in that repository or search for work arounds or bug fixes.

**Comment by imranq** [comment]
Finally got it to work...I had to delete the eigen_types.h file from g2opy and remake the build with python3.6. For some reason Eigen was giving me trouble.
